#!/usr/bin/env bash

cd /home/developer/${INTELLIJ_VERSION}/config/plugins/

# Adding the predefined preferences to IDEA
#cp /home/developer/.jdk.table.xml /home/developer/${INTELLIJ_VERSION}/config/options/jdk.table.xml

exec /opt/intellij/bin/idea.sh
